# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.model_api import ModelApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_models_get(self):
        """Test case for models_get

        """
        pass

    def test_models_id_get(self):
        """Test case for models_id_get

        """
        pass

    def test_models_id_put(self):
        """Test case for models_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
