# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.avtale_giro_merged_file import AvtaleGiroMergedFile  # noqa: E501
from swagger_client.rest import ApiException


class TestAvtaleGiroMergedFile(unittest.TestCase):
    """AvtaleGiroMergedFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvtaleGiroMergedFile(self):
        """Test AvtaleGiroMergedFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.avtale_giro_merged_file.AvtaleGiroMergedFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
