# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.employment_leaves import EmploymentLeaves  # noqa: E501
from swagger_client.rest import ApiException


class TestEmploymentLeaves(unittest.TestCase):
    """EmploymentLeaves unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmploymentLeaves(self):
        """Test EmploymentLeaves"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.employment_leaves.EmploymentLeaves()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
