# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.journal_entry_source_serie import JournalEntrySourceSerie  # noqa: E501
from swagger_client.rest import ApiException


class TestJournalEntrySourceSerie(unittest.TestCase):
    """JournalEntrySourceSerie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJournalEntrySourceSerie(self):
        """Test JournalEntrySourceSerie"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.journal_entry_source_serie.JournalEntrySourceSerie()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
