# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wage_type_supplement import WageTypeSupplement  # noqa: E501
from swagger_client.rest import ApiException


class TestWageTypeSupplement(unittest.TestCase):
    """WageTypeSupplement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWageTypeSupplement(self):
        """Test WageTypeSupplement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wage_type_supplement.WageTypeSupplement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
