# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.company_accounting_settings_api import CompanyAccountingSettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyAccountingSettingsApi(unittest.TestCase):
    """CompanyAccountingSettingsApi unit test stubs"""

    def setUp(self):
        self.api = CompanyAccountingSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companyaccountingsettings_get(self):
        """Test case for companyaccountingsettings_get

        """
        pass

    def test_companyaccountingsettings_id_delete(self):
        """Test case for companyaccountingsettings_id_delete

        """
        pass

    def test_companyaccountingsettings_id_get(self):
        """Test case for companyaccountingsettings_id_get

        """
        pass

    def test_companyaccountingsettings_id_put(self):
        """Test case for companyaccountingsettings_id_put

        """
        pass

    def test_companyaccountingsettings_post(self):
        """Test case for companyaccountingsettings_post

        """
        pass

    def test_companyaccountingsettingsactionget_or_create_get(self):
        """Test case for companyaccountingsettingsactionget_or_create_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
