# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.report_definition_api import ReportDefinitionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportDefinitionApi(unittest.TestCase):
    """ReportDefinitionApi unit test stubs"""

    def setUp(self):
        self.api = ReportDefinitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_report_definitions_get(self):
        """Test case for report_definitions_get

        """
        pass

    def test_report_definitions_id_delete(self):
        """Test case for report_definitions_id_delete

        """
        pass

    def test_report_definitions_id_get(self):
        """Test case for report_definitions_id_get

        """
        pass

    def test_report_definitions_id_put(self):
        """Test case for report_definitions_id_put

        """
        pass

    def test_report_definitions_idactionclear_report_cache_delete(self):
        """Test case for report_definitions_idactionclear_report_cache_delete

        """
        pass

    def test_report_definitions_post(self):
        """Test case for report_definitions_post

        """
        pass

    def test_report_definitionsactionget_all_reports_get(self):
        """Test case for report_definitionsactionget_all_reports_get

        """
        pass

    def test_report_definitionsactionget_custom_reports_get(self):
        """Test case for report_definitionsactionget_custom_reports_get

        """
        pass

    def test_report_definitionsactionload_reports_get(self):
        """Test case for report_definitionsactionload_reports_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
