# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.work_type_api import WorkTypeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkTypeApi(unittest.TestCase):
    """WorkTypeApi unit test stubs"""

    def setUp(self):
        self.api = WorkTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_worktypes_get(self):
        """Test case for worktypes_get

        """
        pass

    def test_worktypes_id_delete(self):
        """Test case for worktypes_id_delete

        """
        pass

    def test_worktypes_id_get(self):
        """Test case for worktypes_id_get

        """
        pass

    def test_worktypes_id_put(self):
        """Test case for worktypes_id_put

        """
        pass

    def test_worktypes_post(self):
        """Test case for worktypes_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
