# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_order_api import CustomerOrderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerOrderApi(unittest.TestCase):
    """CustomerOrderApi unit test stubs"""

    def setUp(self):
        self.api = CustomerOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_get(self):
        """Test case for orders_get

        """
        pass

    def test_orders_id_delete(self):
        """Test case for orders_id_delete

        """
        pass

    def test_orders_id_get(self):
        """Test case for orders_id_get

        """
        pass

    def test_orders_id_put(self):
        """Test case for orders_id_put

        """
        pass

    def test_orders_idactioncalculate_vat_summary_get(self):
        """Test case for orders_idactioncalculate_vat_summary_get

        """
        pass

    def test_orders_idactioncomplete_post(self):
        """Test case for orders_idactioncomplete_post

        """
        pass

    def test_orders_idactionnext_get(self):
        """Test case for orders_idactionnext_get

        """
        pass

    def test_orders_idactionpartly_transfer_to_invoice_post(self):
        """Test case for orders_idactionpartly_transfer_to_invoice_post

        """
        pass

    def test_orders_idactionprevious_get(self):
        """Test case for orders_idactionprevious_get

        """
        pass

    def test_orders_idactionregister_post(self):
        """Test case for orders_idactionregister_post

        """
        pass

    def test_orders_idactionset_customer_order_printstatus_put(self):
        """Test case for orders_idactionset_customer_order_printstatus_put

        """
        pass

    def test_orders_idactiontransfer_to_invoice_post(self):
        """Test case for orders_idactiontransfer_to_invoice_post

        """
        pass

    def test_orders_idactiontransfer_to_invoice_put(self):
        """Test case for orders_idactiontransfer_to_invoice_put

        """
        pass

    def test_orders_post(self):
        """Test case for orders_post

        """
        pass

    def test_ordersactioncalculate_order_summary_post(self):
        """Test case for ordersactioncalculate_order_summary_post

        """
        pass

    def test_ordersactioncalculate_vat_summary_get(self):
        """Test case for ordersactioncalculate_vat_summary_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
