# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.predefined_description import PredefinedDescription  # noqa: E501
from swagger_client.rest import ApiException


class TestPredefinedDescription(unittest.TestCase):
    """PredefinedDescription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPredefinedDescription(self):
        """Test PredefinedDescription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.predefined_description.PredefinedDescription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
