# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bank_service_bank_account import BankServiceBankAccount  # noqa: E501
from swagger_client.rest import ApiException


class TestBankServiceBankAccount(unittest.TestCase):
    """BankServiceBankAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankServiceBankAccount(self):
        """Test BankServiceBankAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bank_service_bank_account.BankServiceBankAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
