# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.aga_zone import AGAZone  # noqa: E501
from swagger_client.rest import ApiException


class TestAGAZone(unittest.TestCase):
    """AGAZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAGAZone(self):
        """Test AGAZone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.aga_zone.AGAZone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
