# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bank_statement_api import BankStatementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBankStatementApi(unittest.TestCase):
    """BankStatementApi unit test stubs"""

    def setUp(self):
        self.api = BankStatementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bankstatements_get(self):
        """Test case for bankstatements_get

        """
        pass

    def test_bankstatements_id_delete(self):
        """Test case for bankstatements_id_delete

        """
        pass

    def test_bankstatements_id_get(self):
        """Test case for bankstatements_id_get

        """
        pass

    def test_bankstatements_id_put(self):
        """Test case for bankstatements_id_put

        """
        pass

    def test_bankstatements_idactioncomplete_post(self):
        """Test case for bankstatements_idactioncomplete_post

        """
        pass

    def test_bankstatements_idactionreopen_post(self):
        """Test case for bankstatements_idactionreopen_post

        """
        pass

    def test_bankstatements_post(self):
        """Test case for bankstatements_post

        """
        pass

    def test_bankstatementsactionaccount_balance_get(self):
        """Test case for bankstatementsactionaccount_balance_get

        """
        pass

    def test_bankstatementsactionaccount_status_get(self):
        """Test case for bankstatementsactionaccount_status_get

        """
        pass

    def test_bankstatementsactionaccount_status_monthly_get(self):
        """Test case for bankstatementsactionaccount_status_monthly_get

        """
        pass

    def test_bankstatementsactionimport_post(self):
        """Test case for bankstatementsactionimport_post

        """
        pass

    def test_bankstatementsactionmatch_items_post(self):
        """Test case for bankstatementsactionmatch_items_post

        """
        pass

    def test_bankstatementsactionpreview_post(self):
        """Test case for bankstatementsactionpreview_post

        """
        pass

    def test_bankstatementsactionsuggest_match_post(self):
        """Test case for bankstatementsactionsuggest_match_post

        """
        pass

    def test_bankstatementsactiontemplates_get(self):
        """Test case for bankstatementsactiontemplates_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
