# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_accountid_subaccounts_get(self):
        """Test case for accounts_accountid_subaccounts_get

        """
        pass

    def test_accounts_accountid_subaccounts_id_delete(self):
        """Test case for accounts_accountid_subaccounts_id_delete

        """
        pass

    def test_accounts_accountid_subaccounts_id_get(self):
        """Test case for accounts_accountid_subaccounts_id_get

        """
        pass

    def test_accounts_accountid_subaccounts_id_put(self):
        """Test case for accounts_accountid_subaccounts_id_put

        """
        pass

    def test_accounts_accountid_subaccounts_post(self):
        """Test case for accounts_accountid_subaccounts_post

        """
        pass

    def test_accounts_get(self):
        """Test case for accounts_get

        """
        pass

    def test_accounts_id_delete(self):
        """Test case for accounts_id_delete

        """
        pass

    def test_accounts_id_get(self):
        """Test case for accounts_id_get

        """
        pass

    def test_accounts_id_put(self):
        """Test case for accounts_id_put

        """
        pass

    def test_accounts_idactionis_account_used_get(self):
        """Test case for accounts_idactionis_account_used_get

        """
        pass

    def test_accounts_post(self):
        """Test case for accounts_post

        """
        pass

    def test_accountsactionbalance_get(self):
        """Test case for accountsactionbalance_get

        """
        pass

    def test_accountsactionbalance_grouped_get(self):
        """Test case for accountsactionbalance_grouped_get

        """
        pass

    def test_accountsactionbulk_save_put(self):
        """Test case for accountsactionbulk_save_put

        """
        pass

    def test_accountsactionget_account_usage_detailed_get(self):
        """Test case for accountsactionget_account_usage_detailed_get

        """
        pass

    def test_accountsactionget_account_usage_get(self):
        """Test case for accountsactionget_account_usage_get

        """
        pass

    def test_accountsactionpayables_by_age_detailed_get(self):
        """Test case for accountsactionpayables_by_age_detailed_get

        """
        pass

    def test_accountsactionpayables_by_age_get(self):
        """Test case for accountsactionpayables_by_age_get

        """
        pass

    def test_accountsactionprofit_and_loss_grouped_get(self):
        """Test case for accountsactionprofit_and_loss_grouped_get

        """
        pass

    def test_accountsactionprofit_and_loss_periodical_get(self):
        """Test case for accountsactionprofit_and_loss_periodical_get

        """
        pass

    def test_accountsactionsaftmapping_accounts_get(self):
        """Test case for accountsactionsaftmapping_accounts_get

        """
        pass

    def test_accountsactionset_account_visibility_group_post(self):
        """Test case for accountsactionset_account_visibility_group_post

        """
        pass

    def test_accountsactionset_saftmappings_put(self):
        """Test case for accountsactionset_saftmappings_put

        """
        pass

    def test_accountsactionsynchronize_ns4102_as_put(self):
        """Test case for accountsactionsynchronize_ns4102_as_put

        """
        pass

    def test_accountsactionvalid_get(self):
        """Test case for accountsactionvalid_get

        """
        pass

    def test_accountsactionvalid_with_hidden_get(self):
        """Test case for accountsactionvalid_with_hidden_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
