# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class BankApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def banks_get(self, **kwargs):  # noqa: E501
        """banks_get  # noqa: E501

        Query Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Bank]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banks_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.banks_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def banks_get_with_http_info(self, **kwargs):  # noqa: E501
        """banks_get  # noqa: E501

        Query Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Bank]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banks_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Bank]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banks_id_delete(self, id, **kwargs):  # noqa: E501
        """banks_id_delete  # noqa: E501

        Delete Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_id_delete(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banks_id_delete_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.banks_id_delete_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def banks_id_delete_with_http_info(self, id, **kwargs):  # noqa: E501
        """banks_id_delete  # noqa: E501

        Delete Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_id_delete_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banks_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `banks_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Bank',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banks_id_get(self, id, **kwargs):  # noqa: E501
        """banks_id_get  # noqa: E501

        Get Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_id_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banks_id_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.banks_id_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def banks_id_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """banks_id_get  # noqa: E501

        Get Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_id_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banks_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `banks_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Bank',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banks_id_put(self, body, id, **kwargs):  # noqa: E501
        """banks_id_put  # noqa: E501

        Update Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_id_put(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Bank body: (required)
        :param int id: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banks_id_put_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.banks_id_put_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def banks_id_put_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """banks_id_put  # noqa: E501

        Update Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_id_put_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Bank body: (required)
        :param int id: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banks_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `banks_id_put`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `banks_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Bank',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banks_post(self, body, **kwargs):  # noqa: E501
        """banks_post  # noqa: E501

        Create Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Bank body: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banks_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.banks_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def banks_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """banks_post  # noqa: E501

        Create Bank  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banks_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Bank body: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banks_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `banks_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Bank',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banksactionget_bank_from_accountnumber_lookup_get(self, bank_account_number, **kwargs):  # noqa: E501
        """banksactionget_bank_from_accountnumber_lookup_get  # noqa: E501

        get-bank-from-accountnumber-lookup Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionget_bank_from_accountnumber_lookup_get(bank_account_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object bank_account_number: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banksactionget_bank_from_accountnumber_lookup_get_with_http_info(bank_account_number, **kwargs)  # noqa: E501
        else:
            (data) = self.banksactionget_bank_from_accountnumber_lookup_get_with_http_info(bank_account_number, **kwargs)  # noqa: E501
            return data

    def banksactionget_bank_from_accountnumber_lookup_get_with_http_info(self, bank_account_number, **kwargs):  # noqa: E501
        """banksactionget_bank_from_accountnumber_lookup_get  # noqa: E501

        get-bank-from-accountnumber-lookup Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionget_bank_from_accountnumber_lookup_get_with_http_info(bank_account_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object bank_account_number: (required)
        :return: Bank
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['bank_account_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banksactionget_bank_from_accountnumber_lookup_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'bank_account_number' is set
        if ('bank_account_number' not in params or
                params['bank_account_number'] is None):
            raise ValueError("Missing the required parameter `bank_account_number` when calling `banksactionget_bank_from_accountnumber_lookup_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bank_account_number' in params:
            path_params['bankAccountNumber'] = params['bank_account_number']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks?action=get-bank-from-accountnumber-lookup', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Bank',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banksactionget_iban_from_accountnumber_lookup_get(self, bank_account_number, **kwargs):  # noqa: E501
        """banksactionget_iban_from_accountnumber_lookup_get  # noqa: E501

        get-iban-from-accountnumber-lookup Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionget_iban_from_accountnumber_lookup_get(bank_account_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object bank_account_number: (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banksactionget_iban_from_accountnumber_lookup_get_with_http_info(bank_account_number, **kwargs)  # noqa: E501
        else:
            (data) = self.banksactionget_iban_from_accountnumber_lookup_get_with_http_info(bank_account_number, **kwargs)  # noqa: E501
            return data

    def banksactionget_iban_from_accountnumber_lookup_get_with_http_info(self, bank_account_number, **kwargs):  # noqa: E501
        """banksactionget_iban_from_accountnumber_lookup_get  # noqa: E501

        get-iban-from-accountnumber-lookup Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionget_iban_from_accountnumber_lookup_get_with_http_info(bank_account_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object bank_account_number: (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['bank_account_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banksactionget_iban_from_accountnumber_lookup_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'bank_account_number' is set
        if ('bank_account_number' not in params or
                params['bank_account_number'] is None):
            raise ValueError("Missing the required parameter `bank_account_number` when calling `banksactionget_iban_from_accountnumber_lookup_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bank_account_number' in params:
            path_params['bankAccountNumber'] = params['bank_account_number']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks?action=get-iban-from-accountnumber-lookup', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banksactionget_iban_upsert_bank_get(self, bank_account_number, **kwargs):  # noqa: E501
        """banksactionget_iban_upsert_bank_get  # noqa: E501

        get-iban-upsert-bank Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionget_iban_upsert_bank_get(bank_account_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object bank_account_number: (required)
        :return: BankData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banksactionget_iban_upsert_bank_get_with_http_info(bank_account_number, **kwargs)  # noqa: E501
        else:
            (data) = self.banksactionget_iban_upsert_bank_get_with_http_info(bank_account_number, **kwargs)  # noqa: E501
            return data

    def banksactionget_iban_upsert_bank_get_with_http_info(self, bank_account_number, **kwargs):  # noqa: E501
        """banksactionget_iban_upsert_bank_get  # noqa: E501

        get-iban-upsert-bank Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionget_iban_upsert_bank_get_with_http_info(bank_account_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object bank_account_number: (required)
        :return: BankData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['bank_account_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banksactionget_iban_upsert_bank_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'bank_account_number' is set
        if ('bank_account_number' not in params or
                params['bank_account_number'] is None):
            raise ValueError("Missing the required parameter `bank_account_number` when calling `banksactionget_iban_upsert_bank_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bank_account_number' in params:
            path_params['bankAccountNumber'] = params['bank_account_number']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks?action=get-iban-upsert-bank', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BankData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banksactionverify_iban_get(self, iban, **kwargs):  # noqa: E501
        """banksactionverify_iban_get  # noqa: E501

        verify-iban Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionverify_iban_get(iban, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object iban: (required)
        :return: bool
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banksactionverify_iban_get_with_http_info(iban, **kwargs)  # noqa: E501
        else:
            (data) = self.banksactionverify_iban_get_with_http_info(iban, **kwargs)  # noqa: E501
            return data

    def banksactionverify_iban_get_with_http_info(self, iban, **kwargs):  # noqa: E501
        """banksactionverify_iban_get  # noqa: E501

        verify-iban Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionverify_iban_get_with_http_info(iban, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object iban: (required)
        :return: bool
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['iban']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banksactionverify_iban_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'iban' is set
        if ('iban' not in params or
                params['iban'] is None):
            raise ValueError("Missing the required parameter `iban` when calling `banksactionverify_iban_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'iban' in params:
            path_params['iban'] = params['iban']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks?action=verify-iban', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='bool',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def banksactionverify_iban_upsert_bank_get(self, iban, **kwargs):  # noqa: E501
        """banksactionverify_iban_upsert_bank_get  # noqa: E501

        verify-iban-upsert-bank Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionverify_iban_upsert_bank_get(iban, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object iban: (required)
        :return: BankData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.banksactionverify_iban_upsert_bank_get_with_http_info(iban, **kwargs)  # noqa: E501
        else:
            (data) = self.banksactionverify_iban_upsert_bank_get_with_http_info(iban, **kwargs)  # noqa: E501
            return data

    def banksactionverify_iban_upsert_bank_get_with_http_info(self, iban, **kwargs):  # noqa: E501
        """banksactionverify_iban_upsert_bank_get  # noqa: E501

        verify-iban-upsert-bank Action  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.banksactionverify_iban_upsert_bank_get_with_http_info(iban, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object iban: (required)
        :return: BankData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['iban']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method banksactionverify_iban_upsert_bank_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'iban' is set
        if ('iban' not in params or
                params['iban'] is None):
            raise ValueError("Missing the required parameter `iban` when calling `banksactionverify_iban_upsert_bank_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'iban' in params:
            path_params['iban'] = params['iban']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/banks?action=verify-iban-upsert-bank', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BankData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
