# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssetReportLineDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'type_id': 'int',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'type': 'Type',
        'type_id': 'TypeID',
        'custom_values': 'CustomValues'
    }

    def __init__(self, type=None, type_id=None, custom_values=None):  # noqa: E501
        """AssetReportLineDTO - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._type_id = None
        self._custom_values = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if type_id is not None:
            self.type_id = type_id
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def type(self):
        """Gets the type of this AssetReportLineDTO.  # noqa: E501


        :return: The type of this AssetReportLineDTO.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AssetReportLineDTO.


        :param type: The type of this AssetReportLineDTO.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def type_id(self):
        """Gets the type_id of this AssetReportLineDTO.  # noqa: E501


        :return: The type_id of this AssetReportLineDTO.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this AssetReportLineDTO.


        :param type_id: The type_id of this AssetReportLineDTO.  # noqa: E501
        :type: int
        """

        self._type_id = type_id

    @property
    def custom_values(self):
        """Gets the custom_values of this AssetReportLineDTO.  # noqa: E501


        :return: The custom_values of this AssetReportLineDTO.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this AssetReportLineDTO.


        :param custom_values: The custom_values of this AssetReportLineDTO.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssetReportLineDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetReportLineDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
