# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssetGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'depreciation_rate': 'int',
        'depreciation_years': 'int',
        'name': 'str',
        'deleted': 'bool',
        'id': 'int',
        'depreciation_account_number': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'code': 'Code',
        'depreciation_rate': 'DepreciationRate',
        'depreciation_years': 'DepreciationYears',
        'name': 'Name',
        'deleted': 'Deleted',
        'id': 'ID',
        'depreciation_account_number': 'DepreciationAccountNumber',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'custom_values': 'CustomValues'
    }

    def __init__(self, code=None, depreciation_rate=None, depreciation_years=None, name=None, deleted=None, id=None, depreciation_account_number=None, updated_by=None, created_by=None, custom_values=None):  # noqa: E501
        """AssetGroup - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._depreciation_rate = None
        self._depreciation_years = None
        self._name = None
        self._deleted = None
        self._id = None
        self._depreciation_account_number = None
        self._updated_by = None
        self._created_by = None
        self._custom_values = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if depreciation_rate is not None:
            self.depreciation_rate = depreciation_rate
        if depreciation_years is not None:
            self.depreciation_years = depreciation_years
        if name is not None:
            self.name = name
        if deleted is not None:
            self.deleted = deleted
        if id is not None:
            self.id = id
        if depreciation_account_number is not None:
            self.depreciation_account_number = depreciation_account_number
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def code(self):
        """Gets the code of this AssetGroup.  # noqa: E501


        :return: The code of this AssetGroup.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this AssetGroup.


        :param code: The code of this AssetGroup.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def depreciation_rate(self):
        """Gets the depreciation_rate of this AssetGroup.  # noqa: E501


        :return: The depreciation_rate of this AssetGroup.  # noqa: E501
        :rtype: int
        """
        return self._depreciation_rate

    @depreciation_rate.setter
    def depreciation_rate(self, depreciation_rate):
        """Sets the depreciation_rate of this AssetGroup.


        :param depreciation_rate: The depreciation_rate of this AssetGroup.  # noqa: E501
        :type: int
        """

        self._depreciation_rate = depreciation_rate

    @property
    def depreciation_years(self):
        """Gets the depreciation_years of this AssetGroup.  # noqa: E501


        :return: The depreciation_years of this AssetGroup.  # noqa: E501
        :rtype: int
        """
        return self._depreciation_years

    @depreciation_years.setter
    def depreciation_years(self, depreciation_years):
        """Sets the depreciation_years of this AssetGroup.


        :param depreciation_years: The depreciation_years of this AssetGroup.  # noqa: E501
        :type: int
        """

        self._depreciation_years = depreciation_years

    @property
    def name(self):
        """Gets the name of this AssetGroup.  # noqa: E501


        :return: The name of this AssetGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AssetGroup.


        :param name: The name of this AssetGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def deleted(self):
        """Gets the deleted of this AssetGroup.  # noqa: E501


        :return: The deleted of this AssetGroup.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this AssetGroup.


        :param deleted: The deleted of this AssetGroup.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def id(self):
        """Gets the id of this AssetGroup.  # noqa: E501


        :return: The id of this AssetGroup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AssetGroup.


        :param id: The id of this AssetGroup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def depreciation_account_number(self):
        """Gets the depreciation_account_number of this AssetGroup.  # noqa: E501


        :return: The depreciation_account_number of this AssetGroup.  # noqa: E501
        :rtype: int
        """
        return self._depreciation_account_number

    @depreciation_account_number.setter
    def depreciation_account_number(self, depreciation_account_number):
        """Sets the depreciation_account_number of this AssetGroup.


        :param depreciation_account_number: The depreciation_account_number of this AssetGroup.  # noqa: E501
        :type: int
        """

        self._depreciation_account_number = depreciation_account_number

    @property
    def updated_by(self):
        """Gets the updated_by of this AssetGroup.  # noqa: E501


        :return: The updated_by of this AssetGroup.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this AssetGroup.


        :param updated_by: The updated_by of this AssetGroup.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this AssetGroup.  # noqa: E501


        :return: The created_by of this AssetGroup.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this AssetGroup.


        :param created_by: The created_by of this AssetGroup.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def custom_values(self):
        """Gets the custom_values of this AssetGroup.  # noqa: E501


        :return: The custom_values of this AssetGroup.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this AssetGroup.


        :param custom_values: The custom_values of this AssetGroup.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssetGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
