# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BankFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accountnumber': 'str',
        'sub_company_id': 'int',
        'parent_fileid': 'int',
        'status_code': 'int',
        'deleted': 'bool',
        'id': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'file_id': 'int',
        'file': 'File',
        'sub_company': 'SubCompany',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'accountnumber': 'Accountnumber',
        'sub_company_id': 'SubCompanyID',
        'parent_fileid': 'ParentFileid',
        'status_code': 'StatusCode',
        'deleted': 'Deleted',
        'id': 'ID',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'file_id': 'FileID',
        'file': 'File',
        'sub_company': 'SubCompany',
        'custom_values': 'CustomValues'
    }

    def __init__(self, accountnumber=None, sub_company_id=None, parent_fileid=None, status_code=None, deleted=None, id=None, updated_by=None, created_by=None, file_id=None, file=None, sub_company=None, custom_values=None):  # noqa: E501
        """BankFile - a model defined in Swagger"""  # noqa: E501
        self._accountnumber = None
        self._sub_company_id = None
        self._parent_fileid = None
        self._status_code = None
        self._deleted = None
        self._id = None
        self._updated_by = None
        self._created_by = None
        self._file_id = None
        self._file = None
        self._sub_company = None
        self._custom_values = None
        self.discriminator = None
        if accountnumber is not None:
            self.accountnumber = accountnumber
        if sub_company_id is not None:
            self.sub_company_id = sub_company_id
        if parent_fileid is not None:
            self.parent_fileid = parent_fileid
        if status_code is not None:
            self.status_code = status_code
        if deleted is not None:
            self.deleted = deleted
        if id is not None:
            self.id = id
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if file_id is not None:
            self.file_id = file_id
        if file is not None:
            self.file = file
        if sub_company is not None:
            self.sub_company = sub_company
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def accountnumber(self):
        """Gets the accountnumber of this BankFile.  # noqa: E501


        :return: The accountnumber of this BankFile.  # noqa: E501
        :rtype: str
        """
        return self._accountnumber

    @accountnumber.setter
    def accountnumber(self, accountnumber):
        """Sets the accountnumber of this BankFile.


        :param accountnumber: The accountnumber of this BankFile.  # noqa: E501
        :type: str
        """

        self._accountnumber = accountnumber

    @property
    def sub_company_id(self):
        """Gets the sub_company_id of this BankFile.  # noqa: E501


        :return: The sub_company_id of this BankFile.  # noqa: E501
        :rtype: int
        """
        return self._sub_company_id

    @sub_company_id.setter
    def sub_company_id(self, sub_company_id):
        """Sets the sub_company_id of this BankFile.


        :param sub_company_id: The sub_company_id of this BankFile.  # noqa: E501
        :type: int
        """

        self._sub_company_id = sub_company_id

    @property
    def parent_fileid(self):
        """Gets the parent_fileid of this BankFile.  # noqa: E501


        :return: The parent_fileid of this BankFile.  # noqa: E501
        :rtype: int
        """
        return self._parent_fileid

    @parent_fileid.setter
    def parent_fileid(self, parent_fileid):
        """Sets the parent_fileid of this BankFile.


        :param parent_fileid: The parent_fileid of this BankFile.  # noqa: E501
        :type: int
        """

        self._parent_fileid = parent_fileid

    @property
    def status_code(self):
        """Gets the status_code of this BankFile.  # noqa: E501


        :return: The status_code of this BankFile.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this BankFile.


        :param status_code: The status_code of this BankFile.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def deleted(self):
        """Gets the deleted of this BankFile.  # noqa: E501


        :return: The deleted of this BankFile.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this BankFile.


        :param deleted: The deleted of this BankFile.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def id(self):
        """Gets the id of this BankFile.  # noqa: E501


        :return: The id of this BankFile.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BankFile.


        :param id: The id of this BankFile.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def updated_by(self):
        """Gets the updated_by of this BankFile.  # noqa: E501


        :return: The updated_by of this BankFile.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this BankFile.


        :param updated_by: The updated_by of this BankFile.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this BankFile.  # noqa: E501


        :return: The created_by of this BankFile.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this BankFile.


        :param created_by: The created_by of this BankFile.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def file_id(self):
        """Gets the file_id of this BankFile.  # noqa: E501


        :return: The file_id of this BankFile.  # noqa: E501
        :rtype: int
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this BankFile.


        :param file_id: The file_id of this BankFile.  # noqa: E501
        :type: int
        """

        self._file_id = file_id

    @property
    def file(self):
        """Gets the file of this BankFile.  # noqa: E501


        :return: The file of this BankFile.  # noqa: E501
        :rtype: File
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this BankFile.


        :param file: The file of this BankFile.  # noqa: E501
        :type: File
        """

        self._file = file

    @property
    def sub_company(self):
        """Gets the sub_company of this BankFile.  # noqa: E501


        :return: The sub_company of this BankFile.  # noqa: E501
        :rtype: SubCompany
        """
        return self._sub_company

    @sub_company.setter
    def sub_company(self, sub_company):
        """Sets the sub_company of this BankFile.


        :param sub_company: The sub_company of this BankFile.  # noqa: E501
        :type: SubCompany
        """

        self._sub_company = sub_company

    @property
    def custom_values(self):
        """Gets the custom_values of this BankFile.  # noqa: E501


        :return: The custom_values of this BankFile.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this BankFile.


        :param custom_values: The custom_values of this BankFile.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BankFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BankFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
