# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Comment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status_code': 'int',
        'deleted': 'bool',
        'entity_type': 'str',
        'author_id': 'int',
        'id': 'int',
        'updated_by': 'str',
        'text': 'str',
        'created_by': 'str',
        'entity_id': 'int',
        'mentioned': 'list[Mentioned]',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'status_code': 'StatusCode',
        'deleted': 'Deleted',
        'entity_type': 'EntityType',
        'author_id': 'AuthorID',
        'id': 'ID',
        'updated_by': 'UpdatedBy',
        'text': 'Text',
        'created_by': 'CreatedBy',
        'entity_id': 'EntityID',
        'mentioned': 'Mentioned',
        'custom_values': 'CustomValues'
    }

    def __init__(self, status_code=None, deleted=None, entity_type=None, author_id=None, id=None, updated_by=None, text=None, created_by=None, entity_id=None, mentioned=None, custom_values=None):  # noqa: E501
        """Comment - a model defined in Swagger"""  # noqa: E501
        self._status_code = None
        self._deleted = None
        self._entity_type = None
        self._author_id = None
        self._id = None
        self._updated_by = None
        self._text = None
        self._created_by = None
        self._entity_id = None
        self._mentioned = None
        self._custom_values = None
        self.discriminator = None
        if status_code is not None:
            self.status_code = status_code
        if deleted is not None:
            self.deleted = deleted
        if entity_type is not None:
            self.entity_type = entity_type
        if author_id is not None:
            self.author_id = author_id
        if id is not None:
            self.id = id
        if updated_by is not None:
            self.updated_by = updated_by
        if text is not None:
            self.text = text
        if created_by is not None:
            self.created_by = created_by
        if entity_id is not None:
            self.entity_id = entity_id
        if mentioned is not None:
            self.mentioned = mentioned
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def status_code(self):
        """Gets the status_code of this Comment.  # noqa: E501


        :return: The status_code of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this Comment.


        :param status_code: The status_code of this Comment.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def deleted(self):
        """Gets the deleted of this Comment.  # noqa: E501


        :return: The deleted of this Comment.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this Comment.


        :param deleted: The deleted of this Comment.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def entity_type(self):
        """Gets the entity_type of this Comment.  # noqa: E501


        :return: The entity_type of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this Comment.


        :param entity_type: The entity_type of this Comment.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def author_id(self):
        """Gets the author_id of this Comment.  # noqa: E501


        :return: The author_id of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id):
        """Sets the author_id of this Comment.


        :param author_id: The author_id of this Comment.  # noqa: E501
        :type: int
        """

        self._author_id = author_id

    @property
    def id(self):
        """Gets the id of this Comment.  # noqa: E501


        :return: The id of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Comment.


        :param id: The id of this Comment.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def updated_by(self):
        """Gets the updated_by of this Comment.  # noqa: E501


        :return: The updated_by of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this Comment.


        :param updated_by: The updated_by of this Comment.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def text(self):
        """Gets the text of this Comment.  # noqa: E501


        :return: The text of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Comment.


        :param text: The text of this Comment.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def created_by(self):
        """Gets the created_by of this Comment.  # noqa: E501


        :return: The created_by of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Comment.


        :param created_by: The created_by of this Comment.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def entity_id(self):
        """Gets the entity_id of this Comment.  # noqa: E501


        :return: The entity_id of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this Comment.


        :param entity_id: The entity_id of this Comment.  # noqa: E501
        :type: int
        """

        self._entity_id = entity_id

    @property
    def mentioned(self):
        """Gets the mentioned of this Comment.  # noqa: E501


        :return: The mentioned of this Comment.  # noqa: E501
        :rtype: list[Mentioned]
        """
        return self._mentioned

    @mentioned.setter
    def mentioned(self, mentioned):
        """Sets the mentioned of this Comment.


        :param mentioned: The mentioned of this Comment.  # noqa: E501
        :type: list[Mentioned]
        """

        self._mentioned = mentioned

    @property
    def custom_values(self):
        """Gets the custom_values of this Comment.  # noqa: E501


        :return: The custom_values of this Comment.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this Comment.


        :param custom_values: The custom_values of this Comment.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Comment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Comment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
