# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FreeAmountSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rest_free_amount': 'int',
        'sub_entities_sums': 'list[SubEntityAgaSums]',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'rest_free_amount': 'RestFreeAmount',
        'sub_entities_sums': 'SubEntitiesSums',
        'custom_values': 'CustomValues'
    }

    def __init__(self, rest_free_amount=None, sub_entities_sums=None, custom_values=None):  # noqa: E501
        """FreeAmountSummary - a model defined in Swagger"""  # noqa: E501
        self._rest_free_amount = None
        self._sub_entities_sums = None
        self._custom_values = None
        self.discriminator = None
        if rest_free_amount is not None:
            self.rest_free_amount = rest_free_amount
        if sub_entities_sums is not None:
            self.sub_entities_sums = sub_entities_sums
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def rest_free_amount(self):
        """Gets the rest_free_amount of this FreeAmountSummary.  # noqa: E501


        :return: The rest_free_amount of this FreeAmountSummary.  # noqa: E501
        :rtype: int
        """
        return self._rest_free_amount

    @rest_free_amount.setter
    def rest_free_amount(self, rest_free_amount):
        """Sets the rest_free_amount of this FreeAmountSummary.


        :param rest_free_amount: The rest_free_amount of this FreeAmountSummary.  # noqa: E501
        :type: int
        """

        self._rest_free_amount = rest_free_amount

    @property
    def sub_entities_sums(self):
        """Gets the sub_entities_sums of this FreeAmountSummary.  # noqa: E501


        :return: The sub_entities_sums of this FreeAmountSummary.  # noqa: E501
        :rtype: list[SubEntityAgaSums]
        """
        return self._sub_entities_sums

    @sub_entities_sums.setter
    def sub_entities_sums(self, sub_entities_sums):
        """Sets the sub_entities_sums of this FreeAmountSummary.


        :param sub_entities_sums: The sub_entities_sums of this FreeAmountSummary.  # noqa: E501
        :type: list[SubEntityAgaSums]
        """

        self._sub_entities_sums = sub_entities_sums

    @property
    def custom_values(self):
        """Gets the custom_values of this FreeAmountSummary.  # noqa: E501


        :return: The custom_values of this FreeAmountSummary.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this FreeAmountSummary.


        :param custom_values: The custom_values of this FreeAmountSummary.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FreeAmountSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FreeAmountSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
