# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JournalSuggestion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'account_id': 'int',
        'match_with_entry_id': 'int',
        'bank_statement_rule_id': 'int',
        'account': 'Account',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'description': 'Description',
        'account_id': 'AccountID',
        'match_with_entry_id': 'MatchWithEntryID',
        'bank_statement_rule_id': 'BankStatementRuleID',
        'account': 'Account',
        'custom_values': 'CustomValues'
    }

    def __init__(self, description=None, account_id=None, match_with_entry_id=None, bank_statement_rule_id=None, account=None, custom_values=None):  # noqa: E501
        """JournalSuggestion - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._account_id = None
        self._match_with_entry_id = None
        self._bank_statement_rule_id = None
        self._account = None
        self._custom_values = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if account_id is not None:
            self.account_id = account_id
        if match_with_entry_id is not None:
            self.match_with_entry_id = match_with_entry_id
        if bank_statement_rule_id is not None:
            self.bank_statement_rule_id = bank_statement_rule_id
        if account is not None:
            self.account = account
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def description(self):
        """Gets the description of this JournalSuggestion.  # noqa: E501


        :return: The description of this JournalSuggestion.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this JournalSuggestion.


        :param description: The description of this JournalSuggestion.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def account_id(self):
        """Gets the account_id of this JournalSuggestion.  # noqa: E501


        :return: The account_id of this JournalSuggestion.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this JournalSuggestion.


        :param account_id: The account_id of this JournalSuggestion.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def match_with_entry_id(self):
        """Gets the match_with_entry_id of this JournalSuggestion.  # noqa: E501


        :return: The match_with_entry_id of this JournalSuggestion.  # noqa: E501
        :rtype: int
        """
        return self._match_with_entry_id

    @match_with_entry_id.setter
    def match_with_entry_id(self, match_with_entry_id):
        """Sets the match_with_entry_id of this JournalSuggestion.


        :param match_with_entry_id: The match_with_entry_id of this JournalSuggestion.  # noqa: E501
        :type: int
        """

        self._match_with_entry_id = match_with_entry_id

    @property
    def bank_statement_rule_id(self):
        """Gets the bank_statement_rule_id of this JournalSuggestion.  # noqa: E501


        :return: The bank_statement_rule_id of this JournalSuggestion.  # noqa: E501
        :rtype: int
        """
        return self._bank_statement_rule_id

    @bank_statement_rule_id.setter
    def bank_statement_rule_id(self, bank_statement_rule_id):
        """Sets the bank_statement_rule_id of this JournalSuggestion.


        :param bank_statement_rule_id: The bank_statement_rule_id of this JournalSuggestion.  # noqa: E501
        :type: int
        """

        self._bank_statement_rule_id = bank_statement_rule_id

    @property
    def account(self):
        """Gets the account of this JournalSuggestion.  # noqa: E501


        :return: The account of this JournalSuggestion.  # noqa: E501
        :rtype: Account
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this JournalSuggestion.


        :param account: The account of this JournalSuggestion.  # noqa: E501
        :type: Account
        """

        self._account = account

    @property
    def custom_values(self):
        """Gets the custom_values of this JournalSuggestion.  # noqa: E501


        :return: The custom_values of this JournalSuggestion.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this JournalSuggestion.


        :param custom_values: The custom_values of this JournalSuggestion.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JournalSuggestion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JournalSuggestion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
