# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MatchCandidate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'closed': 'bool',
        'is_bank_entry': 'bool',
        'id': 'int',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'closed': 'Closed',
        'is_bank_entry': 'IsBankEntry',
        'id': 'ID',
        'custom_values': 'CustomValues'
    }

    def __init__(self, closed=None, is_bank_entry=None, id=None, custom_values=None):  # noqa: E501
        """MatchCandidate - a model defined in Swagger"""  # noqa: E501
        self._closed = None
        self._is_bank_entry = None
        self._id = None
        self._custom_values = None
        self.discriminator = None
        if closed is not None:
            self.closed = closed
        if is_bank_entry is not None:
            self.is_bank_entry = is_bank_entry
        if id is not None:
            self.id = id
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def closed(self):
        """Gets the closed of this MatchCandidate.  # noqa: E501


        :return: The closed of this MatchCandidate.  # noqa: E501
        :rtype: bool
        """
        return self._closed

    @closed.setter
    def closed(self, closed):
        """Sets the closed of this MatchCandidate.


        :param closed: The closed of this MatchCandidate.  # noqa: E501
        :type: bool
        """

        self._closed = closed

    @property
    def is_bank_entry(self):
        """Gets the is_bank_entry of this MatchCandidate.  # noqa: E501


        :return: The is_bank_entry of this MatchCandidate.  # noqa: E501
        :rtype: bool
        """
        return self._is_bank_entry

    @is_bank_entry.setter
    def is_bank_entry(self, is_bank_entry):
        """Sets the is_bank_entry of this MatchCandidate.


        :param is_bank_entry: The is_bank_entry of this MatchCandidate.  # noqa: E501
        :type: bool
        """

        self._is_bank_entry = is_bank_entry

    @property
    def id(self):
        """Gets the id of this MatchCandidate.  # noqa: E501


        :return: The id of this MatchCandidate.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MatchCandidate.


        :param id: The id of this MatchCandidate.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def custom_values(self):
        """Gets the custom_values of this MatchCandidate.  # noqa: E501


        :return: The custom_values of this MatchCandidate.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this MatchCandidate.


        :param custom_values: The custom_values of this MatchCandidate.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchCandidate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchCandidate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
