# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Notification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_entity_type': 'str',
        'message': 'str',
        'sender_display_name': 'str',
        'company_key': 'str',
        'status_code': 'int',
        'deleted': 'bool',
        'entity_type': 'str',
        'company_name': 'str',
        'id': 'int',
        'source_entity_id': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'recipient_id': 'str',
        'entity_id': 'int',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'source_entity_type': 'SourceEntityType',
        'message': 'Message',
        'sender_display_name': 'SenderDisplayName',
        'company_key': 'CompanyKey',
        'status_code': 'StatusCode',
        'deleted': 'Deleted',
        'entity_type': 'EntityType',
        'company_name': 'CompanyName',
        'id': 'ID',
        'source_entity_id': 'SourceEntityID',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'recipient_id': 'RecipientID',
        'entity_id': 'EntityID',
        'custom_values': 'CustomValues'
    }

    def __init__(self, source_entity_type=None, message=None, sender_display_name=None, company_key=None, status_code=None, deleted=None, entity_type=None, company_name=None, id=None, source_entity_id=None, updated_by=None, created_by=None, recipient_id=None, entity_id=None, custom_values=None):  # noqa: E501
        """Notification - a model defined in Swagger"""  # noqa: E501
        self._source_entity_type = None
        self._message = None
        self._sender_display_name = None
        self._company_key = None
        self._status_code = None
        self._deleted = None
        self._entity_type = None
        self._company_name = None
        self._id = None
        self._source_entity_id = None
        self._updated_by = None
        self._created_by = None
        self._recipient_id = None
        self._entity_id = None
        self._custom_values = None
        self.discriminator = None
        if source_entity_type is not None:
            self.source_entity_type = source_entity_type
        if message is not None:
            self.message = message
        if sender_display_name is not None:
            self.sender_display_name = sender_display_name
        if company_key is not None:
            self.company_key = company_key
        if status_code is not None:
            self.status_code = status_code
        if deleted is not None:
            self.deleted = deleted
        if entity_type is not None:
            self.entity_type = entity_type
        if company_name is not None:
            self.company_name = company_name
        if id is not None:
            self.id = id
        if source_entity_id is not None:
            self.source_entity_id = source_entity_id
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if recipient_id is not None:
            self.recipient_id = recipient_id
        if entity_id is not None:
            self.entity_id = entity_id
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def source_entity_type(self):
        """Gets the source_entity_type of this Notification.  # noqa: E501


        :return: The source_entity_type of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._source_entity_type

    @source_entity_type.setter
    def source_entity_type(self, source_entity_type):
        """Sets the source_entity_type of this Notification.


        :param source_entity_type: The source_entity_type of this Notification.  # noqa: E501
        :type: str
        """

        self._source_entity_type = source_entity_type

    @property
    def message(self):
        """Gets the message of this Notification.  # noqa: E501


        :return: The message of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Notification.


        :param message: The message of this Notification.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def sender_display_name(self):
        """Gets the sender_display_name of this Notification.  # noqa: E501


        :return: The sender_display_name of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._sender_display_name

    @sender_display_name.setter
    def sender_display_name(self, sender_display_name):
        """Sets the sender_display_name of this Notification.


        :param sender_display_name: The sender_display_name of this Notification.  # noqa: E501
        :type: str
        """

        self._sender_display_name = sender_display_name

    @property
    def company_key(self):
        """Gets the company_key of this Notification.  # noqa: E501


        :return: The company_key of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._company_key

    @company_key.setter
    def company_key(self, company_key):
        """Sets the company_key of this Notification.


        :param company_key: The company_key of this Notification.  # noqa: E501
        :type: str
        """

        self._company_key = company_key

    @property
    def status_code(self):
        """Gets the status_code of this Notification.  # noqa: E501


        :return: The status_code of this Notification.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this Notification.


        :param status_code: The status_code of this Notification.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def deleted(self):
        """Gets the deleted of this Notification.  # noqa: E501


        :return: The deleted of this Notification.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this Notification.


        :param deleted: The deleted of this Notification.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def entity_type(self):
        """Gets the entity_type of this Notification.  # noqa: E501


        :return: The entity_type of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this Notification.


        :param entity_type: The entity_type of this Notification.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def company_name(self):
        """Gets the company_name of this Notification.  # noqa: E501


        :return: The company_name of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this Notification.


        :param company_name: The company_name of this Notification.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def id(self):
        """Gets the id of this Notification.  # noqa: E501


        :return: The id of this Notification.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Notification.


        :param id: The id of this Notification.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def source_entity_id(self):
        """Gets the source_entity_id of this Notification.  # noqa: E501


        :return: The source_entity_id of this Notification.  # noqa: E501
        :rtype: int
        """
        return self._source_entity_id

    @source_entity_id.setter
    def source_entity_id(self, source_entity_id):
        """Sets the source_entity_id of this Notification.


        :param source_entity_id: The source_entity_id of this Notification.  # noqa: E501
        :type: int
        """

        self._source_entity_id = source_entity_id

    @property
    def updated_by(self):
        """Gets the updated_by of this Notification.  # noqa: E501


        :return: The updated_by of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this Notification.


        :param updated_by: The updated_by of this Notification.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this Notification.  # noqa: E501


        :return: The created_by of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Notification.


        :param created_by: The created_by of this Notification.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def recipient_id(self):
        """Gets the recipient_id of this Notification.  # noqa: E501


        :return: The recipient_id of this Notification.  # noqa: E501
        :rtype: str
        """
        return self._recipient_id

    @recipient_id.setter
    def recipient_id(self, recipient_id):
        """Sets the recipient_id of this Notification.


        :param recipient_id: The recipient_id of this Notification.  # noqa: E501
        :type: str
        """

        self._recipient_id = recipient_id

    @property
    def entity_id(self):
        """Gets the entity_id of this Notification.  # noqa: E501


        :return: The entity_id of this Notification.  # noqa: E501
        :rtype: int
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this Notification.


        :param entity_id: The entity_id of this Notification.  # noqa: E501
        :type: int
        """

        self._entity_id = entity_id

    @property
    def custom_values(self):
        """Gets the custom_values of this Notification.  # noqa: E501


        :return: The custom_values of this Notification.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this Notification.


        :param custom_values: The custom_values of this Notification.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Notification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Notification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
