# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProcessFileLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_count': 'int',
        'message': 'str',
        'company_key': 'str',
        'file_name': 'str',
        'status_code': 'int',
        'deleted': 'bool',
        'company_name': 'str',
        'entity_instance_id': 'str',
        'file_type': 'int',
        'id': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'user_identity': 'str',
        'company_id': 'int',
        'file_id': 'int',
        'entity_name': 'str',
        'company': 'Company',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'entity_count': 'EntityCount',
        'message': 'Message',
        'company_key': 'CompanyKey',
        'file_name': 'FileName',
        'status_code': 'StatusCode',
        'deleted': 'Deleted',
        'company_name': 'CompanyName',
        'entity_instance_id': 'EntityInstanceID',
        'file_type': 'FileType',
        'id': 'ID',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'user_identity': 'UserIdentity',
        'company_id': 'CompanyID',
        'file_id': 'FileID',
        'entity_name': 'EntityName',
        'company': 'Company',
        'custom_values': 'CustomValues'
    }

    def __init__(self, entity_count=None, message=None, company_key=None, file_name=None, status_code=None, deleted=None, company_name=None, entity_instance_id=None, file_type=None, id=None, updated_by=None, created_by=None, user_identity=None, company_id=None, file_id=None, entity_name=None, company=None, custom_values=None):  # noqa: E501
        """ProcessFileLog - a model defined in Swagger"""  # noqa: E501
        self._entity_count = None
        self._message = None
        self._company_key = None
        self._file_name = None
        self._status_code = None
        self._deleted = None
        self._company_name = None
        self._entity_instance_id = None
        self._file_type = None
        self._id = None
        self._updated_by = None
        self._created_by = None
        self._user_identity = None
        self._company_id = None
        self._file_id = None
        self._entity_name = None
        self._company = None
        self._custom_values = None
        self.discriminator = None
        if entity_count is not None:
            self.entity_count = entity_count
        if message is not None:
            self.message = message
        if company_key is not None:
            self.company_key = company_key
        if file_name is not None:
            self.file_name = file_name
        if status_code is not None:
            self.status_code = status_code
        if deleted is not None:
            self.deleted = deleted
        if company_name is not None:
            self.company_name = company_name
        if entity_instance_id is not None:
            self.entity_instance_id = entity_instance_id
        if file_type is not None:
            self.file_type = file_type
        if id is not None:
            self.id = id
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if user_identity is not None:
            self.user_identity = user_identity
        if company_id is not None:
            self.company_id = company_id
        if file_id is not None:
            self.file_id = file_id
        if entity_name is not None:
            self.entity_name = entity_name
        if company is not None:
            self.company = company
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def entity_count(self):
        """Gets the entity_count of this ProcessFileLog.  # noqa: E501


        :return: The entity_count of this ProcessFileLog.  # noqa: E501
        :rtype: int
        """
        return self._entity_count

    @entity_count.setter
    def entity_count(self, entity_count):
        """Sets the entity_count of this ProcessFileLog.


        :param entity_count: The entity_count of this ProcessFileLog.  # noqa: E501
        :type: int
        """

        self._entity_count = entity_count

    @property
    def message(self):
        """Gets the message of this ProcessFileLog.  # noqa: E501


        :return: The message of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ProcessFileLog.


        :param message: The message of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def company_key(self):
        """Gets the company_key of this ProcessFileLog.  # noqa: E501


        :return: The company_key of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._company_key

    @company_key.setter
    def company_key(self, company_key):
        """Sets the company_key of this ProcessFileLog.


        :param company_key: The company_key of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._company_key = company_key

    @property
    def file_name(self):
        """Gets the file_name of this ProcessFileLog.  # noqa: E501


        :return: The file_name of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this ProcessFileLog.


        :param file_name: The file_name of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def status_code(self):
        """Gets the status_code of this ProcessFileLog.  # noqa: E501


        :return: The status_code of this ProcessFileLog.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this ProcessFileLog.


        :param status_code: The status_code of this ProcessFileLog.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def deleted(self):
        """Gets the deleted of this ProcessFileLog.  # noqa: E501


        :return: The deleted of this ProcessFileLog.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this ProcessFileLog.


        :param deleted: The deleted of this ProcessFileLog.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def company_name(self):
        """Gets the company_name of this ProcessFileLog.  # noqa: E501


        :return: The company_name of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this ProcessFileLog.


        :param company_name: The company_name of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def entity_instance_id(self):
        """Gets the entity_instance_id of this ProcessFileLog.  # noqa: E501


        :return: The entity_instance_id of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._entity_instance_id

    @entity_instance_id.setter
    def entity_instance_id(self, entity_instance_id):
        """Sets the entity_instance_id of this ProcessFileLog.


        :param entity_instance_id: The entity_instance_id of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._entity_instance_id = entity_instance_id

    @property
    def file_type(self):
        """Gets the file_type of this ProcessFileLog.  # noqa: E501


        :return: The file_type of this ProcessFileLog.  # noqa: E501
        :rtype: int
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type):
        """Sets the file_type of this ProcessFileLog.


        :param file_type: The file_type of this ProcessFileLog.  # noqa: E501
        :type: int
        """

        self._file_type = file_type

    @property
    def id(self):
        """Gets the id of this ProcessFileLog.  # noqa: E501


        :return: The id of this ProcessFileLog.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProcessFileLog.


        :param id: The id of this ProcessFileLog.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def updated_by(self):
        """Gets the updated_by of this ProcessFileLog.  # noqa: E501


        :return: The updated_by of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this ProcessFileLog.


        :param updated_by: The updated_by of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this ProcessFileLog.  # noqa: E501


        :return: The created_by of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ProcessFileLog.


        :param created_by: The created_by of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def user_identity(self):
        """Gets the user_identity of this ProcessFileLog.  # noqa: E501


        :return: The user_identity of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._user_identity

    @user_identity.setter
    def user_identity(self, user_identity):
        """Sets the user_identity of this ProcessFileLog.


        :param user_identity: The user_identity of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._user_identity = user_identity

    @property
    def company_id(self):
        """Gets the company_id of this ProcessFileLog.  # noqa: E501


        :return: The company_id of this ProcessFileLog.  # noqa: E501
        :rtype: int
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this ProcessFileLog.


        :param company_id: The company_id of this ProcessFileLog.  # noqa: E501
        :type: int
        """

        self._company_id = company_id

    @property
    def file_id(self):
        """Gets the file_id of this ProcessFileLog.  # noqa: E501


        :return: The file_id of this ProcessFileLog.  # noqa: E501
        :rtype: int
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this ProcessFileLog.


        :param file_id: The file_id of this ProcessFileLog.  # noqa: E501
        :type: int
        """

        self._file_id = file_id

    @property
    def entity_name(self):
        """Gets the entity_name of this ProcessFileLog.  # noqa: E501


        :return: The entity_name of this ProcessFileLog.  # noqa: E501
        :rtype: str
        """
        return self._entity_name

    @entity_name.setter
    def entity_name(self, entity_name):
        """Sets the entity_name of this ProcessFileLog.


        :param entity_name: The entity_name of this ProcessFileLog.  # noqa: E501
        :type: str
        """

        self._entity_name = entity_name

    @property
    def company(self):
        """Gets the company of this ProcessFileLog.  # noqa: E501


        :return: The company of this ProcessFileLog.  # noqa: E501
        :rtype: Company
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this ProcessFileLog.


        :param company: The company of this ProcessFileLog.  # noqa: E501
        :type: Company
        """

        self._company = company

    @property
    def custom_values(self):
        """Gets the custom_values of this ProcessFileLog.  # noqa: E501


        :return: The custom_values of this ProcessFileLog.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this ProcessFileLog.


        :param custom_values: The custom_values of this ProcessFileLog.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProcessFileLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessFileLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
