# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransitionFlow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transition_id': 'int',
        'from_status_id': 'int',
        'deleted': 'bool',
        'entity_type': 'str',
        'is_depricated': 'bool',
        'id': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'to_status_id': 'int',
        'from_status': 'Status',
        'to_status': 'Status',
        'transition': 'Transition',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'transition_id': 'TransitionID',
        'from_status_id': 'FromStatusID',
        'deleted': 'Deleted',
        'entity_type': 'EntityType',
        'is_depricated': 'IsDepricated',
        'id': 'ID',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'to_status_id': 'ToStatusID',
        'from_status': 'FromStatus',
        'to_status': 'ToStatus',
        'transition': 'Transition',
        'custom_values': 'CustomValues'
    }

    def __init__(self, transition_id=None, from_status_id=None, deleted=None, entity_type=None, is_depricated=None, id=None, updated_by=None, created_by=None, to_status_id=None, from_status=None, to_status=None, transition=None, custom_values=None):  # noqa: E501
        """TransitionFlow - a model defined in Swagger"""  # noqa: E501
        self._transition_id = None
        self._from_status_id = None
        self._deleted = None
        self._entity_type = None
        self._is_depricated = None
        self._id = None
        self._updated_by = None
        self._created_by = None
        self._to_status_id = None
        self._from_status = None
        self._to_status = None
        self._transition = None
        self._custom_values = None
        self.discriminator = None
        if transition_id is not None:
            self.transition_id = transition_id
        if from_status_id is not None:
            self.from_status_id = from_status_id
        if deleted is not None:
            self.deleted = deleted
        if entity_type is not None:
            self.entity_type = entity_type
        if is_depricated is not None:
            self.is_depricated = is_depricated
        if id is not None:
            self.id = id
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if to_status_id is not None:
            self.to_status_id = to_status_id
        if from_status is not None:
            self.from_status = from_status
        if to_status is not None:
            self.to_status = to_status
        if transition is not None:
            self.transition = transition
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def transition_id(self):
        """Gets the transition_id of this TransitionFlow.  # noqa: E501


        :return: The transition_id of this TransitionFlow.  # noqa: E501
        :rtype: int
        """
        return self._transition_id

    @transition_id.setter
    def transition_id(self, transition_id):
        """Sets the transition_id of this TransitionFlow.


        :param transition_id: The transition_id of this TransitionFlow.  # noqa: E501
        :type: int
        """

        self._transition_id = transition_id

    @property
    def from_status_id(self):
        """Gets the from_status_id of this TransitionFlow.  # noqa: E501


        :return: The from_status_id of this TransitionFlow.  # noqa: E501
        :rtype: int
        """
        return self._from_status_id

    @from_status_id.setter
    def from_status_id(self, from_status_id):
        """Sets the from_status_id of this TransitionFlow.


        :param from_status_id: The from_status_id of this TransitionFlow.  # noqa: E501
        :type: int
        """

        self._from_status_id = from_status_id

    @property
    def deleted(self):
        """Gets the deleted of this TransitionFlow.  # noqa: E501


        :return: The deleted of this TransitionFlow.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this TransitionFlow.


        :param deleted: The deleted of this TransitionFlow.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def entity_type(self):
        """Gets the entity_type of this TransitionFlow.  # noqa: E501


        :return: The entity_type of this TransitionFlow.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this TransitionFlow.


        :param entity_type: The entity_type of this TransitionFlow.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def is_depricated(self):
        """Gets the is_depricated of this TransitionFlow.  # noqa: E501


        :return: The is_depricated of this TransitionFlow.  # noqa: E501
        :rtype: bool
        """
        return self._is_depricated

    @is_depricated.setter
    def is_depricated(self, is_depricated):
        """Sets the is_depricated of this TransitionFlow.


        :param is_depricated: The is_depricated of this TransitionFlow.  # noqa: E501
        :type: bool
        """

        self._is_depricated = is_depricated

    @property
    def id(self):
        """Gets the id of this TransitionFlow.  # noqa: E501


        :return: The id of this TransitionFlow.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TransitionFlow.


        :param id: The id of this TransitionFlow.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def updated_by(self):
        """Gets the updated_by of this TransitionFlow.  # noqa: E501


        :return: The updated_by of this TransitionFlow.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this TransitionFlow.


        :param updated_by: The updated_by of this TransitionFlow.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this TransitionFlow.  # noqa: E501


        :return: The created_by of this TransitionFlow.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this TransitionFlow.


        :param created_by: The created_by of this TransitionFlow.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def to_status_id(self):
        """Gets the to_status_id of this TransitionFlow.  # noqa: E501


        :return: The to_status_id of this TransitionFlow.  # noqa: E501
        :rtype: int
        """
        return self._to_status_id

    @to_status_id.setter
    def to_status_id(self, to_status_id):
        """Sets the to_status_id of this TransitionFlow.


        :param to_status_id: The to_status_id of this TransitionFlow.  # noqa: E501
        :type: int
        """

        self._to_status_id = to_status_id

    @property
    def from_status(self):
        """Gets the from_status of this TransitionFlow.  # noqa: E501


        :return: The from_status of this TransitionFlow.  # noqa: E501
        :rtype: Status
        """
        return self._from_status

    @from_status.setter
    def from_status(self, from_status):
        """Sets the from_status of this TransitionFlow.


        :param from_status: The from_status of this TransitionFlow.  # noqa: E501
        :type: Status
        """

        self._from_status = from_status

    @property
    def to_status(self):
        """Gets the to_status of this TransitionFlow.  # noqa: E501


        :return: The to_status of this TransitionFlow.  # noqa: E501
        :rtype: Status
        """
        return self._to_status

    @to_status.setter
    def to_status(self, to_status):
        """Sets the to_status of this TransitionFlow.


        :param to_status: The to_status of this TransitionFlow.  # noqa: E501
        :type: Status
        """

        self._to_status = to_status

    @property
    def transition(self):
        """Gets the transition of this TransitionFlow.  # noqa: E501


        :return: The transition of this TransitionFlow.  # noqa: E501
        :rtype: Transition
        """
        return self._transition

    @transition.setter
    def transition(self, transition):
        """Sets the transition of this TransitionFlow.


        :param transition: The transition of this TransitionFlow.  # noqa: E501
        :type: Transition
        """

        self._transition = transition

    @property
    def custom_values(self):
        """Gets the custom_values of this TransitionFlow.  # noqa: E501


        :return: The custom_values of this TransitionFlow.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this TransitionFlow.


        :param custom_values: The custom_values of this TransitionFlow.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransitionFlow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransitionFlow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
