# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TravelType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'invoice_account': 'int',
        'foreign_type_id': 'str',
        'status_code': 'int',
        'deleted': 'bool',
        'foreign_description': 'str',
        'id': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'wage_type_number': 'int',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'description': 'Description',
        'invoice_account': 'InvoiceAccount',
        'foreign_type_id': 'ForeignTypeID',
        'status_code': 'StatusCode',
        'deleted': 'Deleted',
        'foreign_description': 'ForeignDescription',
        'id': 'ID',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'wage_type_number': 'WageTypeNumber',
        'custom_values': 'CustomValues'
    }

    def __init__(self, description=None, invoice_account=None, foreign_type_id=None, status_code=None, deleted=None, foreign_description=None, id=None, updated_by=None, created_by=None, wage_type_number=None, custom_values=None):  # noqa: E501
        """TravelType - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._invoice_account = None
        self._foreign_type_id = None
        self._status_code = None
        self._deleted = None
        self._foreign_description = None
        self._id = None
        self._updated_by = None
        self._created_by = None
        self._wage_type_number = None
        self._custom_values = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if invoice_account is not None:
            self.invoice_account = invoice_account
        if foreign_type_id is not None:
            self.foreign_type_id = foreign_type_id
        if status_code is not None:
            self.status_code = status_code
        if deleted is not None:
            self.deleted = deleted
        if foreign_description is not None:
            self.foreign_description = foreign_description
        if id is not None:
            self.id = id
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if wage_type_number is not None:
            self.wage_type_number = wage_type_number
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def description(self):
        """Gets the description of this TravelType.  # noqa: E501


        :return: The description of this TravelType.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TravelType.


        :param description: The description of this TravelType.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def invoice_account(self):
        """Gets the invoice_account of this TravelType.  # noqa: E501


        :return: The invoice_account of this TravelType.  # noqa: E501
        :rtype: int
        """
        return self._invoice_account

    @invoice_account.setter
    def invoice_account(self, invoice_account):
        """Sets the invoice_account of this TravelType.


        :param invoice_account: The invoice_account of this TravelType.  # noqa: E501
        :type: int
        """

        self._invoice_account = invoice_account

    @property
    def foreign_type_id(self):
        """Gets the foreign_type_id of this TravelType.  # noqa: E501


        :return: The foreign_type_id of this TravelType.  # noqa: E501
        :rtype: str
        """
        return self._foreign_type_id

    @foreign_type_id.setter
    def foreign_type_id(self, foreign_type_id):
        """Sets the foreign_type_id of this TravelType.


        :param foreign_type_id: The foreign_type_id of this TravelType.  # noqa: E501
        :type: str
        """

        self._foreign_type_id = foreign_type_id

    @property
    def status_code(self):
        """Gets the status_code of this TravelType.  # noqa: E501


        :return: The status_code of this TravelType.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this TravelType.


        :param status_code: The status_code of this TravelType.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def deleted(self):
        """Gets the deleted of this TravelType.  # noqa: E501


        :return: The deleted of this TravelType.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this TravelType.


        :param deleted: The deleted of this TravelType.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def foreign_description(self):
        """Gets the foreign_description of this TravelType.  # noqa: E501


        :return: The foreign_description of this TravelType.  # noqa: E501
        :rtype: str
        """
        return self._foreign_description

    @foreign_description.setter
    def foreign_description(self, foreign_description):
        """Sets the foreign_description of this TravelType.


        :param foreign_description: The foreign_description of this TravelType.  # noqa: E501
        :type: str
        """

        self._foreign_description = foreign_description

    @property
    def id(self):
        """Gets the id of this TravelType.  # noqa: E501


        :return: The id of this TravelType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TravelType.


        :param id: The id of this TravelType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def updated_by(self):
        """Gets the updated_by of this TravelType.  # noqa: E501


        :return: The updated_by of this TravelType.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this TravelType.


        :param updated_by: The updated_by of this TravelType.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this TravelType.  # noqa: E501


        :return: The created_by of this TravelType.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this TravelType.


        :param created_by: The created_by of this TravelType.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def wage_type_number(self):
        """Gets the wage_type_number of this TravelType.  # noqa: E501


        :return: The wage_type_number of this TravelType.  # noqa: E501
        :rtype: int
        """
        return self._wage_type_number

    @wage_type_number.setter
    def wage_type_number(self, wage_type_number):
        """Sets the wage_type_number of this TravelType.


        :param wage_type_number: The wage_type_number of this TravelType.  # noqa: E501
        :type: int
        """

        self._wage_type_number = wage_type_number

    @property
    def custom_values(self):
        """Gets the custom_values of this TravelType.  # noqa: E501


        :return: The custom_values of this TravelType.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this TravelType.


        :param custom_values: The custom_values of this TravelType.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TravelType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TravelType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
