# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Worker(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'int',
        'business_relation_id': 'int',
        'status_code': 'int',
        'deleted': 'bool',
        'id': 'int',
        'updated_by': 'str',
        'created_by': 'str',
        'employee_id': 'int',
        'info': 'BusinessRelation',
        'relations': 'list[WorkRelation]',
        'custom_values': 'CustomValues'
    }

    attribute_map = {
        'user_id': 'UserID',
        'business_relation_id': 'BusinessRelationID',
        'status_code': 'StatusCode',
        'deleted': 'Deleted',
        'id': 'ID',
        'updated_by': 'UpdatedBy',
        'created_by': 'CreatedBy',
        'employee_id': 'EmployeeID',
        'info': 'Info',
        'relations': 'Relations',
        'custom_values': 'CustomValues'
    }

    def __init__(self, user_id=None, business_relation_id=None, status_code=None, deleted=None, id=None, updated_by=None, created_by=None, employee_id=None, info=None, relations=None, custom_values=None):  # noqa: E501
        """Worker - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._business_relation_id = None
        self._status_code = None
        self._deleted = None
        self._id = None
        self._updated_by = None
        self._created_by = None
        self._employee_id = None
        self._info = None
        self._relations = None
        self._custom_values = None
        self.discriminator = None
        if user_id is not None:
            self.user_id = user_id
        if business_relation_id is not None:
            self.business_relation_id = business_relation_id
        if status_code is not None:
            self.status_code = status_code
        if deleted is not None:
            self.deleted = deleted
        if id is not None:
            self.id = id
        if updated_by is not None:
            self.updated_by = updated_by
        if created_by is not None:
            self.created_by = created_by
        if employee_id is not None:
            self.employee_id = employee_id
        if info is not None:
            self.info = info
        if relations is not None:
            self.relations = relations
        if custom_values is not None:
            self.custom_values = custom_values

    @property
    def user_id(self):
        """Gets the user_id of this Worker.  # noqa: E501


        :return: The user_id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Worker.


        :param user_id: The user_id of this Worker.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def business_relation_id(self):
        """Gets the business_relation_id of this Worker.  # noqa: E501


        :return: The business_relation_id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._business_relation_id

    @business_relation_id.setter
    def business_relation_id(self, business_relation_id):
        """Sets the business_relation_id of this Worker.


        :param business_relation_id: The business_relation_id of this Worker.  # noqa: E501
        :type: int
        """

        self._business_relation_id = business_relation_id

    @property
    def status_code(self):
        """Gets the status_code of this Worker.  # noqa: E501


        :return: The status_code of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this Worker.


        :param status_code: The status_code of this Worker.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def deleted(self):
        """Gets the deleted of this Worker.  # noqa: E501


        :return: The deleted of this Worker.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this Worker.


        :param deleted: The deleted of this Worker.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def id(self):
        """Gets the id of this Worker.  # noqa: E501


        :return: The id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Worker.


        :param id: The id of this Worker.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def updated_by(self):
        """Gets the updated_by of this Worker.  # noqa: E501


        :return: The updated_by of this Worker.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this Worker.


        :param updated_by: The updated_by of this Worker.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this Worker.  # noqa: E501


        :return: The created_by of this Worker.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Worker.


        :param created_by: The created_by of this Worker.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def employee_id(self):
        """Gets the employee_id of this Worker.  # noqa: E501


        :return: The employee_id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._employee_id

    @employee_id.setter
    def employee_id(self, employee_id):
        """Sets the employee_id of this Worker.


        :param employee_id: The employee_id of this Worker.  # noqa: E501
        :type: int
        """

        self._employee_id = employee_id

    @property
    def info(self):
        """Gets the info of this Worker.  # noqa: E501


        :return: The info of this Worker.  # noqa: E501
        :rtype: BusinessRelation
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this Worker.


        :param info: The info of this Worker.  # noqa: E501
        :type: BusinessRelation
        """

        self._info = info

    @property
    def relations(self):
        """Gets the relations of this Worker.  # noqa: E501


        :return: The relations of this Worker.  # noqa: E501
        :rtype: list[WorkRelation]
        """
        return self._relations

    @relations.setter
    def relations(self, relations):
        """Sets the relations of this Worker.


        :param relations: The relations of this Worker.  # noqa: E501
        :type: list[WorkRelation]
        """

        self._relations = relations

    @property
    def custom_values(self):
        """Gets the custom_values of this Worker.  # noqa: E501


        :return: The custom_values of this Worker.  # noqa: E501
        :rtype: CustomValues
        """
        return self._custom_values

    @custom_values.setter
    def custom_values(self, custom_values):
        """Sets the custom_values of this Worker.


        :param custom_values: The custom_values of this Worker.  # noqa: E501
        :type: CustomValues
        """

        self._custom_values = custom_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Worker, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Worker):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
